### ISSUE TITLE
Current issues with 1.9 making the viewing experience worse.

### ISSUE THREAD

**Issue by DaveKap** [younesaassila/ttv-lol-pro#114]
Some of these issues were true in 1.8 too, likely due to changes Twitch has been making that we can't keep up with with this current method of ad blocking.

1. When an ad plays and the extension changes stream quality, it sometimes pauses the stream and never plays it again.
2. When the extension blocks an ad, it sometimes fails to change the quality of the stream back to default or previously selected qualities.
3. When the extension blocks an ad, it sometimes disables FFZ's audio compressor.
4. When the extension blocks a pre-roll ad, it sometimes takes the entire length of the ad play to actually start playing the stream.
5. Occasionally the extension will fail to close the quality setting window.

Perhaps this is all just symptoms of this blocking method and the extension can't fix any of it but I figured I'd list it out since I couldn't find anyone else reporting these issues.

**Comment by younesaassila** [comment]
Do you use the VAFT or Video Swap New scripts? These issues seem related. TTV LOL PRO just proxies the requests to ad-free countries and resets the player when a midroll ad is detected (doesn't mess with the quality).

I do agree though that the current ad-blocking methods are not reliable. Apparently VAFT (extension not script) with its PR 96 is working great. I'm also thinking of changing the TTV LOL PRO proxies options to now use proxy lists sorted by most reliable servers perhaps? Since Twitch apparently still serve ads to ad-free countries if the server is making too many requests.

**Comment by DaveKap** [comment]
Ah, it's possible it's twitch  ad-block, which works for VODs I watch but stays on when I'm not watching VODs. I wonder if I can filter that to work only on /video URLs so it can avoid live streams. Otherwise, I keep uBlock disabled so I do not believe it's a script running issue.

**Comment by DaveKap** [comment]
Yep, it was the Twitch AdBlock extension causing the issue. Still don't know how to ensure it's only enabled on /video URLs but I'm closing this issue!
