### ISSUE TITLE
Waterfox Classic compatibilty past 1.8.1.

### ISSUE THREAD

**Issue by tordenflesk** [younesaassila/ttv-lol-pro#143]
1.8.1: https://i.imgur.com/9qt7tj5.png
1.9.2: https://i.imgur.com/9OF5Lfa.png

Neither seem to do much in the way of blocking ads.

**Comment by younesaassila** [comment]
Your 1.9.2 install seems broken. Make sure to follow the [installation guide](https://github.com/younesaassila/ttv-lol-pro#installation) and to download the assets from [the release itself](https://github.com/younesaassila/ttv-lol-pro/releases/tag/v1.9.2) rather than from GitHub's green "Download" button.

If the default proxy is not working for you, please look at the [Discussions page](https://github.com/younesaassila/ttv-lol-pro/discussions) where you'll find other proxies.
