### ISSUE TITLE
Make VPNs and other proxy extensions work with the extension (Chrome)

### ISSUE THREAD

**Issue by younesaassila** [younesaassila/ttv-lol-pro#165]

**Comment by ghost** [comment]
**Blocked by the implementation & rollout of Manifest V3.**

**Comment by younesaassila** [comment]
> **Blocked by the implementation & rollout of Manifest V3.**

Absolutely not

**Comment by Ashesh3** [comment]
One possible workaround is to add a quick toggle to the extension, if toggled off, It will give proxy controls back to Chrome using an implementation similar to how SwitchyOmega does: [SwitchyOmega/proxy_impl_settings.coffee#L10](https://github.com/FelisCatus/SwitchyOmega/blob/master/omega-target-chromium-extension/src/module/proxy/proxy_impl_settings.coffee#L14) . Note that this is different from just setting the proxy to `DIRECT`, in that case this extension would force disable other proxy extensions.

The intention of getting TTV lol pro work ALONG with other proxy extension (both enabled and on) is not possible due to the nature of how `pacScript` work. This extension will conflict with other extensions trying to control the proxy settings. Such conflicts are caused by the design of the Chrome browser and thus cannot be avoided. When "TTV lol pro" has a higher priority, only then it can be configured to voluntarily give back the control by using the linked code snipped above. Re-installing this extension should raise its priority, providing a possible workaround.

**Comment by younesaassila** [comment]
@Ashesh3 Thanks for your help! I'll try to see if I can automate this on/off switching by checking for opened Twitch tabs. If none it goes back to OG proxy settings.

Sad to know that using proxy extensions at the same time is not possible. Perhaps if another extension is using a pacScript I can combine both, but yeah can't do for other types of proxy configs.

**Comment by younesaassila** [comment]
Fixed for next release

**Comment by Makezu90** [comment]
so only on chrome? release page say: chromium based browsers should be fixed if im not understand something wrongly, but on opera gx still can't use same time ttv lol pro & Proxy SwitchyOmega.
