### ISSUE TITLE
In Chrome, clicking the extension icon should show which proxy is being used.

### ISSUE THREAD

**Issue by DaveKap** [younesaassila/ttv-lol-pro#170]
It was a really nice feature, back in the v1 days, being able to see which proxy was being used on a stream because at least then we could live-debug whether our proxies were or weren't working and seeing whether or not fallback priority was working. It seems we cannot do that in v2. Is it possible to bring this nice feature back?

**Comment by thinkpad4** [comment]
I too would like this feature added please.

**Comment by younesaassila** [comment]
Added `help wanted` label since I couldn't figure out any Manifest V3-compatible way of achieving this with the `chrome.proxy` API. Workarounds like implementing a custom fallback system where you'd add a `chrome.webRequest.onBeforeRequest` listener to set proxy settings to 1 proxy and catch if the proxy is offline with `chrome.webRequest.onErrorOccurred` to figure out the proxy being used don't work with Manifest V3 due to the removal of `webRequestBlocking`.

I would highly appreciate the help from other developers! Is this even possible with `chrome.proxy`?

**Comment by ghost** [comment]
> Added `help wanted` label since I couldn't figure out any Manifest V3-compatible way of achieving this with the `chrome.proxy` API. Workarounds like implementing a custom fallback system where you'd add a `chrome.webRequest.onBeforeRequest` listener to set proxy settings to 1 proxy and catch if the proxy is offline with `chrome.webRequest.onErrorOccurred` to figure out the proxy being used don't work with Manifest V3 due to the removal of `webRequestBlocking`.
> 
> I would highly appreciate the help from other developers! Is this even possible with `chrome.proxy`?

**There is no way of doing this. Even if it was possible, V2 has already been bypassed.**

**Comment by DaveKap** [comment]
Is Manifest V3 such an issue when folks are using Brave to keep V2 intact? Are V2-allowable Chromium builds too low of a market share to bother with?

**Comment by younesaassila** [comment]
@DaveKap The Chrome Web Store only allows MV3 extensions. Also let's be honest, other browser vendors will probably end MV2 support at some point too.

**Comment by younesaassila** [comment]
Alright I found a way to get which proxy was used for a specific request. The channel name => video-weaver URLs mapping is still not implemented.
At least debugging logs have been improved on Chrome

**Comment by younesaassila** [comment]
👀 

![image](https://github.com/younesaassila/ttv-lol-pro/assets/47226184/722b43c5-e49e-4e28-a279-650f9987e524)

**Comment by younesaassila** [comment]
Alright closing this since it has been implemented in 2.1.0 (i.e. the next release) :D
