### ISSUE TITLE
ads showing.

### ISSUE THREAD

**Issue by DannyDarth** [younesaassila/ttv-lol-pro#18]
Had an ad come through while watching a followed channel.

**Comment by younesaassila** [comment]
I'm not sure what you mean by "followed channel". Did you mean a channel you're subbed to?

If you're seeing ads, it means TTV LOL's server is experiencing issues, and since I'm not part of the official dev team, I would advise you to report this issue on the official TTV LOL GitHub repo or their Discord server.

**Comment by younesaassila** [comment]
Also, you can check whether or not the stream was redirected through TTV LOL's server by opening the popup and checking what it's reporting (green dot or red dot, with a quick confirmation or error message respectively).

If it's red it means TTV LOL's API is down, if green then API is working but might show ads depending on proxy location available ads and other stuff

**Comment by DannyDarth** [comment]
ah ok it was green
