### ISSUE TITLE
Chrome TTV LOL PRO v2 extension permissions.

### ISSUE THREAD

**Issue by Divzed** [younesaassila/ttv-lol-pro#189]
Is there reason why Chrome TTV LOL PRO v2 has permissions to "Read and change all your data on all websites"?
![1](https://github.com/younesaassila/ttv-lol-pro/assets/104203796/c601afb4-0efc-4c98-a334-fbb59198f44c)
It looks sketchy and basically allows extension to do anything what it wants on every visited website and is enabled all the time. Why?

Meanwhile FFZ extension for example is only allowed on twitch domain/subdomains and is disabled automatically on any other visited website & doesn't require permissions to "Read and change all your data on all websites".
![2](https://github.com/younesaassila/ttv-lol-pro/assets/104203796/021f2ec3-f4bd-44d9-a299-b7ccb147fcae)
![3](https://github.com/younesaassila/ttv-lol-pro/assets/104203796/a9affbca-3ea6-4042-b6b8-baee727d0568)
So can I get explanation, please?

**Comment by younesaassila** [comment]
Your images are broken unfortunately.
You can find the extension permissions in manifest.chromium.json, where you'll find the extension only asks for \*.twitch.tv and \*.ttvnw.net permissions
I don't know where you get that "Access to all websites" from

**Comment by younesaassila** [comment]
This is caused by the `chrome.proxy` API the extension uses. As usual, Chrome always uses the worst sounding permission descriptions possible. If you check the PAC file at `src/common/ts/updateProxySettings.ts`, you'll see the extension only proxies Twitch related requests. Even then, because of HTTPS, the proxy server can only see the domain name. The traffic in itself is encrypted.
