### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JH2535** [younesaassila/ttv-lol-pro#20]
I appreciate what you are doing here, it looks like you have made a nice wrapper around the ttv-lol stuff to give users an improved UX. 

One thing I was worried about was sending token information through to ttv-lol, and I saw you added an option to remove that from any requests (my typescript knowledge is limited) - however when reading through the code I noticed it wasn't on by default, which means - if I'm understanding correctly - there is a moment in time between when a user loads up twitch with your extension and prior to clicking this checkbox, where it is indeed sending this information. Which kind of makes the checkbox somewhat useless as the server would have already gotten the token and potentially stored it somewhere - yeah it does remove the information eventually (once you have checked the box) but thats kind of like me telling you my pin is 3849, my pin is 3849, my pin is ****, my pin is ****, my pin is ****. I think you can deduce what my pin currently is even through its now blanked out...

As someone who is *somewhat* knowledgable about this I know I can load your extension before ever booting up twitch and setting the option to be on, but for the rest is it possible to make it so *before anything is done* the user is asked if they want to enable this option? (or enable it by default - assuming that works) Thank you for your work.

**Comment by younesaassila** [comment]
Hey, thanks for your issue!

TTV LOL PRO is working with two constraints:
- TTV LOL's API requires the token and a valid signature for VODs (I assume because Twitch requires it to check for subscription etc.)
- Removing the token from live stream requests could impact the available stream quality options (in previous testing)

For the latter, I'm not quite sure if this issue was due to bad testing on my part (as I also played around with HLS manifest queries that could have impacted that), so new testing has got to be done on that for sure!

To satisfy those constraints and offer the most ad-free experience by default, the token is stripped down of sensitive information for live streams by default (`device_id`, `user_id`, and `user_ip` token properties, code: https://github.com/younesaassila/ttv-lol-pro/blob/main/src/background/handlers/onBeforeRequest.ts#L56) and for VODs the token is sent as is (due to constraint no. 1).

I know this isn't an ideal default behavior, which is why the add-on offers the option to remove the token from all requests (thus breaking VODs). I'm opened to suggestions on how to improve that default behavior.

Right now I'm thinking if testing shows no impact on available qualities after removing token for live streams perhaps splitting the "Remove token" option in two options "Remove token for live streams" and "Remove token for VODs" and have the first one enabled by default could be better?

**Comment by JH2535** [comment]
>To satisfy those constraints and offer the most ad-free experience by default, the token is stripped down of sensitive information for live streams by default

I screwed up when reading it - my appologise. My eyes glanced over the [else-if](https://github.com/younesaassila/ttv-lol-pro/blob/a48d784a56f199c65df0918bb56feffce25b2be1/src/background/handlers/onBeforeRequest.ts#L55) and assumed that all of this was contingent on [store.state.removeTokenFromRequests](https://github.com/younesaassila/ttv-lol-pro/blob/a48d784a56f199c65df0918bb56feffce25b2be1/src/background/handlers/onBeforeRequest.ts#L53)  which appears to be set to [false by default](https://github.com/younesaassila/ttv-lol-pro/blob/a48d784a56f199c65df0918bb56feffce25b2be1/src/store/index.ts#L12) . Re-reading it I can see that you have indeed stripped these out for [when the type isn't a vod](https://github.com/younesaassila/ttv-lol-pro/blob/a48d784a56f199c65df0918bb56feffce25b2be1/src/background/handlers/onBeforeRequest.ts#L16) which is really the best you can do (as you stated).

> Right now I'm thinking if testing shows no impact on available qualities after removing token for live streams perhaps splitting the "Remove token" option in two options "Remove token for live streams" and "Remove token for VODs" and have the first one enabled by default could be better?

Personally - I don't see re-directing to twitch-lol for vods as being neccessary as ublock origin seems to do a good enough job of stripping ads out of vods. I think rather than splitting the option up - keeping it as it currently is but allowing the user to disable proxies for vods (and setting that to be on by default) might be a good way to deal with this. You could also automatically remove the token information entirely if in testing it doesn't effect quality when this option is selected.

**Comment by berkant** [comment]
I always thought VODs were ad free (or, at least, **server**-ad free). Are you sure those aren't client ads?

**Comment by younesaassila** [comment]
@berkant There's definitely ads on VODs, but I've never heard of client ads. Would you mind explaining what those are?

**Comment by berkant** [comment]
> @berkant There's definitely ads on VODs, but I've never heard of client ads. Would you mind explaining what those are?

Those are ads that your browser directly requests from ad network and plays on fill. Twitch defaults to server ads; nonetheless, they keep periodically probing your browser for client ads. And if that works (it only works if you don't use a general purpose ad blocker because those ad networks and player SDKs have well-known endpoints which are included in basically any filter list), a Spade event is sent to notify Twitch that your browser can play client ads (and thus, you don't have ad blocker). A few hours later you will see that your Usher token is now `server_ads: false`.

**Comment by younesaassila** [comment]
Thank you for the detailed explanation! As pointed out by @JH2535, I think the best solution with this in mind is to stop proxying VODs by default.

If VODs don't rely on server ads, it does make me wonder why TTV LOL proxies them 🤔

**Comment by younesaassila** [comment]
Did a bit of testing and it doesn't seem like removing the token impacts the available stream qualities. Removing all query params from the URL does however, which I think is what led me to initially believe the token removal was at fault.

Since there's no impact, the token will now be removed for live streams. There's also no longer a reason for the "Remove token from requests" option to exist since there's now a "Disable VOD proxying" option enabled by default. Disabling it would show a confirmation prompt about sending the token to TTV LOL's API server. I believe very few people would disable it.

I know the wording is important so that users understand the consequences of disabling this option, so I'm open to feedback about it:

- Confirmation message shown when disabling option: https://github.com/younesaassila/ttv-lol-pro/blob/362789ec57f46f4348d07b210fab67d6fac430f6/src/options/options.ts#L102
- Option description: https://github.com/younesaassila/ttv-lol-pro/blob/362789ec57f46f4348d07b210fab67d6fac430f6/src/options/page.html#L41-L44

**Comment by younesaassila** [comment]
Now merged and published in v1.4.0
