### ISSUE TITLE
Need better fallbacks when a proxy goes down. (Chrome)

### ISSUE THREAD

**Issue by DaveKap** [younesaassila/ttv-lol-pro#207]
Today I had the proxy stop connecting which caused my stream to buffer and give Error #2000. It didn't seem like I was reconnecting any time soon so I figured I would watch the stream without the plugin and just deal with having ads. Unfortunately, the only way to accomplish this is by disabling the extension completely via Chrome's extension page. This issue is sort of a 2-parter.

Firstly, no Chrome extension should work if I right click the extension's icon and choose "This can read and change site data" -> "When you click the extension." It's strange to me that I'm still getting Error #2000 on Twitch streams when I have this explicitly set and the extension's icon is showing a disabled state. Am I wrong about how I'm interpreting Chrome's use of this functionality?

Secondly, I would consider it a bug that streams simply glitch out into Error #2000 when a proxy isn't available. It would make more sense if the fallback state was to simply let ads through.

Let me know if you would like debug information for any of this. I didn't include it since this doesn't feel like something my specific situation was causing. I understand if neither of these things can be fixed if Manifest V3 is getting in the way of development, just figured I'd report them anyway.

**Comment by gearsfanftw** [comment]
im in the same boat today has been hell on twitch

**Comment by zGato** [comment]
If the #2000 error just happened it's normal, my provider just changed the IP of one of my loadbalancers and shoud be fixed in 10 minutes.

Chrome proxy.api modifies the whole browser proxy settings, so basically site permissions are not needed at all for Chrome. To completely disable the extension you need to disable it completely from chrome://extensions

The fallback system works, but I don't think it expects for a loadbalancer to go down for a whole hour. Restarting your browser will assign you a different one and once you get an slot you'll be in. Click the red reload button until you get in. 

I have not tried the fallback system a lot, but seems to work on my end in specific cases.

**Comment by gearsfanftw** [comment]
ty for the quick response i appreciate it

**Comment by DaveKap** [comment]
Agreed, thanks for the speedy reply. I saw that the location of the proxy changed and figured it was a known quantity outage.
