### ISSUE TITLE
Add uBlock Origin recommendation to add-on store descriptions

### ISSUE THREAD

**Issue by younesaassila** [younesaassila/ttv-lol-pro#241]

**Comment by kodiakhub** [comment]
@younesaassila uBO is best for english users, i agree with that. However, AdGuard is best for specific foreign languages (AdGuard Japanese, Turkish filter etc.) because uBO does not fully compatibility AdGuard syntaxes yet. Also, AdGuard blocks ads same as uBO for Twitch, you can test it if you want. If you agree too, AdGuard should be recommended especially for specific languages. 👍
