### ISSUE TITLE
Very rarely Proxying at all on firefox

### ISSUE THREAD

**Issue by BobOrKlaus** [younesaassila/ttv-lol-pro#248]
Just like the Title says, i often get midroll ads now because the proxy isnt "working?" (idk how proxies work exactly so forgive me) 

Proxied: 6 | [Not proxied]: 2222 for example, it connects 6 times every time and then refuses to work, does not stop ads from showing when opening new tab either

**Comment by zGato** [comment]
Please read the [FAQ](https://github.com/younesaassila/ttv-lol-pro/blob/v2/FAQ.md#q-i-dont-get-any-pre-rolls-but-i-always-get-hit-by-mid-rolls)

The Proxy all requests proxy (chrome.api) will be soon limited by a lot, due to it's high costs & maintenance involved. So using it is just worse than using Firefox.

Which types of ads are you seeing? purple "Commercial break in progress" ads or normal ads?
