### ISSUE TITLE
[Request] Remove interaction with non-player pages or whitelisted channels

### ISSUE THREAD

**Issue by GamertechAU** [younesaassila/ttv-lol-pro#250]
**Is your feature request related to a problem? Please describe.**
(Firefox) When the extension is enabled, loading the dashboard, directory, whitelisted channels etc are slowed down noticeably. It can also prevent the dashboard player loading at all unless you whitelist your own channel.

**Describe the solution you'd like**
If possible when a whitelisted channel or non-player page is opened, the extension not interact with it. Even when a channel is whitelisted, the extension still proxies 1 request and slows down page/player load by several seconds sometimes.

Eliminating excess proxy requests would also hopefully reduce a little load on the proxy servers. (unless it's required anyway)

**Describe alternatives you've considered**
Disabling the extension makes page/player loads instant again, but ofc brings back ads in non-subbed channels.

Disabling "Use my TTV LOL PRO passport" or adjusting any other settings in the options panel has no effect on load times.

**Additional context**
https://www.twitch.tv/directory/*
https://dashboard.twitch.tv/* etc

**Comment by younesaassila** [comment]
Unfortunately some requests have to be proxied (e.g. passport requests) even for whitelisted channels in the case you switch streams from a whitelisted channel to a non-whitelisted channel in the same tab.
~~In my testing, I did see an extra video weaver request being proxied at the very beginning of a whitelisted stream loading in a new tab. I don't know if this can be fixed though since this is due to the video weaver request happening before the Usher response containing weaver links for a channel is processed by the content script (race condition?).~~ _(Fixed in v2.2.0)_

**Comment by younesaassila** [comment]
I've added additional checks to ignore Usher and Video Weaver requests from hosts other than www.twitch.tv and m.twitch.tv. This should make the dashboard load a bit faster (though other important requests like Passport, if any, will still be proxied)
I'll consider this as fixed for v2.2.0, closing

**Comment by GamertechAU** [comment]
Thank you :)
