### ISSUE TITLE
Enabling the extension breaks the twitch player

### ISSUE THREAD

**Issue by jqpeijgo** [younesaassila/ttv-lol-pro#252]
**Describe the bug**
Enabling TTV LOL PRO breaks the player, the twitch player never load when after enabling the extension despite disabling all other extensions

**To Reproduce**

1. Just enabling the extension 

**Expected behavior**
for the player to load 

**Screenshots**
https://imgur.com/a/SFDdZMf

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser [Edge]
- Version [Version 116.0.1938.81 (Official build) (64-bit)]

**Additional context**

**Comment by TheRayJohnson** [comment]
This is detailed heavily in #130 and might just be waiting for slots or space to become available. For me I've now had to just disabled TTV LOL PRO cause I'm unable to watch more than 5 minutes straight, missed a lot of WSOW final POVs on TTV.

As of today, I have now installed Firefox Stable just to get a ad-free experience on Twitch. Working wonders.

A few of us need to team up and chip in a few cents together for a private host! I'd be interested :)

also see [I have constant buffering, streams appear as offline](https://github.com/younesaassila/ttv-lol-pro/blob/v2/FAQ.md#q-i-have-constant-buffering-streams-appear-as-offline-)..

**Comment by PatientXero** [comment]
The creator has no interest in adding additional proxies due to funding issues. This project will eventually end up dead like the original TTV LOL project.

**Comment by jqpeijgo** [comment]
Bummer. Thanks for letting me know.

**Comment by TheRayJohnson** [comment]
> The creator has no interest in adding additional proxies due to funding issues. This project will eventually end up dead like the original TTV LOL project.

Yep :(

Myself, I was more referring to hosting our own community proxy, splitting the cost between X number of members. Until I can find some people interested in doing that I've switched to Firefox just for watching Twitch. Not had any buffering, pausing or random refreshing (yet).

**Comment by PatientXero** [comment]
If there as a Patreon for it, say $2-$5 a pop per person per month, that might cover the costs. Hosting through Online, Leaseweb, NForce, etc. doesn't cost too much.

**Comment by TheRayJohnson** [comment]
> If there as a Patreon for it, say $2-$5 a pop per person per month, that might cover the costs.

Sounds like a good idea and a good way to handle it even inc Patreon's fees. I'd be down and interested.

**Comment by SlyCooperReloadCoded** [comment]
Good to know it's just a limitation.  I can't watch at all on any browser, even if I let it try for 3 hours straight.  Is there really no way to block ads anymore, at all?  Surely this isn't the end of Twitch adblock as a whole.

**Comment by zGato** [comment]
There's already the proxies for donators. Costs only $1/month.
If you guys want to make your own "proxy" network, just be aware, 1 proxy is not enough :)

Read from here for the "funding problems" https://github.com/younesaassila/ttv-lol-pro/issues/247#issuecomment-1722551134
In the +2 months the Chrome proxy was on full power (costing $80USD in total) we recieved nowhere near that amount, it's unsustainable and lost money from my pocket. Once I get a job I'll reconsider paying that amount, for now, I have no time for everything going on my life.

I'm still hosting TTVLOL-like proxies for completely free, TTVLOL didn't die for funding reasons. 

I've already said this a few times, Firefox public proxy for TTV LOL PRO V2 is going to be maintained until Twitch patches it or some other rare thing happens. TTV LOL-like proxies (V1) from cdn-perfprod.com are still being maintained by me, and they're highly used aswell, yet, I've not asked a single penny from those, as I tank them out, and will never ask a penny for V1 proxies, yet, V2 is expensive to host (specially if you want good performance all around the globe). V1 is everywhere except South America (most likely coming soon), Oceania (no plans yet) and Africa (makes no sense, they have no ads there basically). Making V2 anycasted would cost me around 60-80$/month for just the loadbalancers, and add up 20$ for the proxies itself.
Oh and wait, we forgot about outside the EU, we need to pay more, as some people buffer when proxying to Helsinki (RU closest Twitch CDN), so we need to apply routing tricks for US people, oh wait, it doesn't work for everyone either.

So then we have to pay around $20/month more just for the US people, assuming 1 star reviews will come as routing tricks don't work for everyone.
Oh and other $20/month for Asia, other $20/month for South America, ...

If anyone has better ideas / cheaper ways to host 5000 simultaneous streams (Chrome) and 1200 (Firefox) then suggestions are welcome. I've already tried a lot of things, we need atleast Ryzen 9 CPUs, a truck load of RAM, bandwidth unlimited with no FUP (as we'll be using more than 100-150TB / month), and other stuff (such as a proxy provider that doesn't care about bandwidth and can offer atleast 100-150 proxies for us to use)

If anyone still thinks I don't do stuff because I don't want, you're completely wrong. I would love to give the best experience to everyone for this, Chrome public proxy wasn't even initially provided (check first V2 releases) but I've created and hosted it for courtesy. Still, tried my best to try being sustainable (or atleast to a level where I would be able to pay the rest), still, it's not possible, and these 2 months with Chrome proxy with top of the notch hardware has proven me. Ask yourself why there's noone hosting V2 proxies (not even V1 proxies, only luminousttv). You need to thank people fighting for Twitch instead of complaining about a "service" no one gave you. This is not your classic YouTube adblocker, those already existed for Twitch, and well, they don't exist anymore because they got patched.

**Comment by TheRayJohnson** [comment]
> Good to know it's just a limitation. I can't watch at all on any browser, even if I let it try for 3 hours straight. Is there really no way to block ads anymore, at all? Surely this isn't the end of Twitch adblock as a whole.

Strange! No issues on Firefox for me only started yesterday though, I'm UK based.

> There's already the proxies for donators. Costs only $1/month. If you guys want to make your own "proxy" network, just be aware, 1 proxy is not enough :)

Is the donators proxy working though? I prefer Chrome but only Firefox is working and I hate it lol.


> Read from here for the "funding problems" [#247 (comment)](https://github.com/younesaassila/ttv-lol-pro/issues/247#issuecomment-1722551134) In the +2 months the Chrome proxy was on full power (costing $80USD in total) we recieved nowhere near that amount, it's unsustainable and lost money from my pocket. Once I get a job I'll reconsider paying that amount, for now, I have no time for everything going on my life.

$80 total? I feel I could cover that in google adSense income depending how many people that $80 serves/covers? 

I'd reach out on [LowEndTalk](https://lowendtalk.com/categories/requests) (if u aren't aware of the forums already) with your requirements and a few providers on there have given me epic deals - plus they hate Ads lol.

I got AMD Ryzen 9 7950X 16-Core Processor, 16GB Memory / Unlimited BW / Read | 1.11 GB/s (2.1k) / Write 1.17 GB/s (2.2k) /  8.74 ms / 958.25 Mbps / 998.27 Mbps* for just $99/yr as a crazy offer, no downtime yet! 

* tested using network-speed.xyz.

**Comment by SlyCooperReloadCoded** [comment]
I guess what I'm asking is why do we need this setup for Twitch ads but not for YouTube, reddit, or any other site?

**Comment by zGato** [comment]
Donators have the best infrastructure with some neat features. They do work indeed, with native support for US, Asia and South American users (as Twitch CDN for them is not Russia but US/Asia/SA using experimental routing tricks whilst proxying to non ad-free countries)

Your deal can be nice and very good, but I do need at least 2-4 cores dedicated, 4-8GB of RAM and truly unlimited. So my last provider gave me that with a 10Gbit uplink and didn't bother me about crazy amounts of used bandwidth, they just obviously applied their ToS and removed my DDoS protected IP, which I don't need and totally understand. 

Regarding users, the last update to Chrome was able to handle around 5000 simultaneous streams (counting unique users, so if 1 user opened 2 streams it would count as 1 either way)

**Comment by berkant** [comment]
@zGato  Is there a technical reason why the project employs network-level proxies (i.e. Squid) instead of building a programmable proxy to bridge Twitch with the added benefits of surgical caching capabilities? I noticed that playlists returned by Usher are not IP-bound, so why not cache & serve them in response to a multitude of requests coming in? Having to blindly reach Twitch's servers on every request must indeed be expensive.

**Comment by zGato** [comment]
> @zGato Is there a technical reason why the project employs network-level proxies (i.e. Squid) instead of building a programmable proxy to bridge Twitch with the added benefits of surgical caching capabilities? I noticed that playlists returned by Usher are not IP-bound, so why not cache & serve them in response to a multitude of requests coming in?

Caching is completely disabled, also Twitch uses HTTPS requests so there's no point. Requests are bound to your user logged in, so not good to cache them.

V1 system uses an API "relay-like", but as you can see, doesn't work for some people anymore. There's no point on developing or trying to develop an API for V2 when Twitch is going to patch it instantly. And, based on my experience, there's no API "relay-like" alternative anymore, as the heavy packets are weavers and we proxy them because those are the ones who ads are embedded into. 

Altough there's a possible way of anonymizing the stream playback token and all the data required to get a stream playlist and the purple ads due to Twitch knowing it's a proxy being triggered much late. Still, no intentions from me or Younes to implement it and hasn't been tested, as we also doubt it will work.

**Comment by SlyCooperReloadCoded** [comment]
Does this being closed mean it's fixed?  I use Firefox and Opera GX which don't have any VPN settings or anything like that, so the fix that mentioned this issue doesn't apply to me.

**Comment by TheRayJohnson** [comment]
> Does this being closed mean it's fixed? I use Firefox and Opera GX which don't have any VPN settings or anything like that, so the fix that mentioned this issue doesn't apply to me.

Not possible to be fixed as stated above and no time or interest. No intentions (or time) from the devs to attempt things.

Rent your own proxy, try the donators proxy (not sure where u sign up) or try something new 

https://github.com/younesaassila/ttv-lol-pro/issues/252#issuecomment-1723030363

https://github.com/younesaassila/ttv-lol-pro/blob/v2/FAQ.md#q-i-have-constant-buffering-streams-appear-as-offline-
