### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by DannyDarth** [younesaassila/ttv-lol-pro#26]
Getting this a lot since the update:

https://i.imgur.com/KfGYuEf.png

**Comment by younesaassila** [comment]
Seems like TTV LOL's API has been having issues lately. Error #2000 is impossible to fix on the browser side alone, so it's up to TTV LOL's developers to improve their server's reliability. This isn't caused by the recent TTV LOL PRO update since I haven't touched the code for redirects/error prevention.
