### ISSUE TITLE
2.2.3/2.3 - Getting Twitch ads on Firefox

### ISSUE THREAD

**Issue by Anony400** [younesaassila/ttv-lol-pro#293]
This add-on has worked well for quite a long time. However, in the last 24 hours, I now get midroll ads. I'm going to send the log via the add-on options. I'm using latest version of Firefox browser.

**Comment by younesaassila** [comment]
Hi there,

The Firefox proxy has been down for the last hour. We're very sorry about this. zGato will fix the problem as soon as he can.

This week could be a bit rough on the proxies because of all the Chromium users now using the same backend as Firefox. If by the end of the week we see that this setup is just not working (downtime, buffering), we'll start limiting Chromium users.

**Comment by mlane3** [comment]
![image](https://github.com/younesaassila/ttv-lol-pro/assets/1785885/3e2e7e39-6b7b-49aa-bbaf-7242160d1723)
Hope this picture helps.  I am going to try to download the latest version of the app just in case.
The ad I am getting are 1) Blurry  2) No sound 3) Pre-roll
P.S.  I don't know much about ad blocker.  I found this through Ublocker reddit and then the twitch ad solutions github.

**Comment by mlane3** [comment]
younesaassila...  I tried the manual install version. Its a bit glitch but still works.   Below are the settings I used:
![image](https://github.com/younesaassila/ttv-lol-pro/assets/1785885/40977b01-9165-4cbe-9b27-502dcceb81ec)

The only issue is that the page take like forever (1-2 minutes) to load.   However,  I am assuming it just blocking adss.

**Comment by younesaassila** [comment]
Proxies can be a bit slow at peak hours
