### ISSUE TITLE
Would it be possible to allow other proxies to be added?

### ISSUE THREAD

**Issue by thinkpad4** [younesaassila/ttv-lol-pro#30]
I know you have the dropdown list for ttvlol and local custom, but what about if I wanted to add another address, not a local one?  
Would you be able to add that option to the extension?
Thank you very much

**Comment by younesaassila** [comment]
The "Local Server" option is more meant for debugging, but I'm not opposed to having a list of custom proxies in Options. The only issue is those proxies would need to use the same routes as TTV LOL's API (`/playlist` and `/vod`)

**Comment by thinkpad4** [comment]
I wanted to try using Luminous TTV and the dev said that as of the latest release it supports TTVLOL API Protocols.

**Comment by younesaassila** [comment]
Nice! Will look into it later. This wouldn't be very hard to implement I believe

**Comment by thinkpad4** [comment]
If you want to test it try the public luminous one ` https://eu.luminous.dev`

**Comment by younesaassila** [comment]
Okay so I refactored the Options's page code to easily manage multiple lists. Thankfully, the code was already made to support multiple servers and picking the first one to successfully respond to a `GET /ping` request.

Right now the "Server list" in the "Options" page looks like this:
![image](https://user-images.githubusercontent.com/47226184/207901852-371aa805-efa5-43a5-83d4-1d2dad1a927a.png)

You can add servers that have priority over TTV LOL's API and fallback servers in case the API is down. TTV LOL's API cannot be removed from the list (since this is **TTV LOL** PRO after all, and to avoir users removing the server and encountering issues).

The changes are not yet live, I'm pushing all of this to a development branch until I implement #21 as well.

**Comment by AlyoshaVasilieva** [comment]
I don't mind if my servers are there by default, but I'll note that while I have downtime alerts on them I can't guarantee they won't break or something.

**Comment by younesaassila** [comment]
The default server list will only contain `https://api.ttv.lol`. Would be difficult to have different defaults depending on users region.

>  On a side note, did they work just as well as the TTVLOL proxy?

In my tests the `as` server worked great, while I was getting pre-rolls with the `eu` server.

**Comment by younesaassila** [comment]
Now available in v1.5.0 🎉

**Comment by thinkpad4** [comment]
This is PERFECT, Thank you very mush
