### ISSUE TITLE
Error #3

### ISSUE THREAD

**Issue by 3laws** [younesaassila/ttv-lol-pro#326]
**Describe the bug**
Unable to watch stream.

**Screenshots**
![image](https://github.com/younesaassila/ttv-lol-pro/assets/4267075/09992fef-3688-417d-856a-c805296864e8)
on [nicewigg](https://www.twitch.tv/nicewigg)

**Desktop (please complete the following information):**

- OS: Linux Arch 6.9
- Browser: Firefox 126.0
- Version 2.3.7
 
**Additional context**
May be on sponsored streams only.

**Comment by zGato** [comment]
Our intentions are not to bypass any of these intentional blocks, channel viewing bans, ...
**This is not an error the extension causes, but the proxy choice.**
You should consider getting your own proxy in a country where the streamer allows viewers from & most likely a proxy that is from a residential ISP if you want to try to bypass those.
This is from our Wiki page.
![image](https://github.com/younesaassila/ttv-lol-pro/assets/88756568/9c3ede73-fba6-4074-93a2-7d143983a1b9)
