### ISSUE TITLE
Infinite Loading Screen during ads since 05/20/24

### ISSUE THREAD

**Issue by sapphoandherdick** [younesaassila/ttv-lol-pro#331]
**Describe the bug**
When viewing twitch, when an ad plays, you either get an infinite loading screen (black screen with a animated circle) or you get a purple background with "commercial break in progress." All other parts of twitch are functional.

**To Reproduce**
1. Go to twitch
2. Wait for an ad to play or go to a streamer that has pre-roll ads.
3. Get infinite loading screen
4. Become sad.

**Expected behavior**
no ads or infinite loading screen.

**Screenshots**
![firefox_977Fm4AGXt](https://github.com/younesaassila/ttv-lol-pro/assets/170652981/b1d5650c-d9c3-42b9-a1a0-eaffa6be6a1f)

(I paused to take the screenshot)

**Desktop (please complete the following information):**

- OS: Windows 10 19045.4412
- Browser: Firefox 126.0 64 bit

**Smartphone (please complete the following information):**
Did not test on smart phone.

**Additional context**
Thank you for the wonderful extension, check your reviews on Firefox extension website, others are experiencing the same issue.

**Comment by sighingslider** [comment]
As far as I can tell, there was a problem with the V2 public proxies 3 days ago on [May 20th, 2024](https://status.perfprod.com/incident/372178) which affected everyone since then. But it seems to be _mostly_ working again on my end, at least on Firefox!

If it's still not working for you after reinstalling the extension and clearing the browser cache, then this might be a different issue.

**Comment by zGato** [comment]
Commercial break in progress screens can't really be bypassed with public proxies, and there will never a guarantee they will. It's Twitch capping the public proxies and serving those ads instead of real ones (because Russia in this case is ad-free) when a certain threshold of users/connections are made to that proxy.
https://wiki.cdn-perfprod.com/guides/extension/troubleshooting#i-get-commercial-break-in-progress-a-ds

You're most likely having connectivity issues with the public proxy when it buffers, and unfortunately again, not much I can do. Public proxies are provided "as is" with no guarantees, and this extension relies on proxies (as it's the main thing it does, proxying twitch stuff). I see not many reports of connectivity issues with the proxy, so I must say it's most likely due to your ISP bad peering with non-nearby countries.

**Comment by sapphoandherdick** [comment]
> As far as I can tell, there was a problem with the V2 public proxies 3 days ago on [May 20th, 2024](https://status.perfprod.com/incident/372178) which affected everyone since then. But it seems to be _mostly_ working again on my end, at least on Firefox!
> 
> If it's still not working for you after reinstalling the extension and clearing the browser cache, then this might be a different issue.

Looks sorted now, so thank you!
