### ISSUE TITLE
Recent vaft/video-swap-new update breaks script injection

### ISSUE THREAD

**Issue by younesaassila** [younesaassila/ttv-lol-pro#334]
In the meantime, please only use 1 Twitch adblocker at the same time.

**Comment by ketcham1009** [comment]
Also not working in Firefox

**Comment by pixeltris** [comment]
Fixed by https://github.com/pixeltris/TwitchAdSolutions/commit/144bc99a619aff738030c7d7de1ed833d43c2514?w=1

**Comment by younesaassila** [comment]
> Fixed by https://github.com/pixeltris/TwitchAdSolutions/commit/144bc99a619aff738030c7d7de1ed833d43c2514?w=1

Thank you very much!

**Comment by pixeltris** [comment]
I had to break it again due to https://github.com/pixeltris/TwitchAdSolutions/issues/277

I essentially changed it to `if (window.Worker.toString().includes('twitch')) { return; }` which is checked when the script loads rather than when DOM loads as background web pages would load workers before the DOM.

You'd need to do something similar in https://github.com/younesaassila/ttv-lol-pro/blob/v2/src/page/page.ts

**Comment by younesaassila** [comment]
~~@pixeltris No worries, any specific reason as to why check for `"twitch"` specifically? Is this what AdGuard uses?~~
I'm dumb, I thought it would test against the Twitch worker file which has a high probability of containing the word "twitch". Of course the built-in object wouldn't ><'

**Comment by pixeltris** [comment]
Yea in this case it's checking the string representation of the Worker constructor/function for `twitch` as that text is inside the Worker implementation of vaft, video-swap-new, AdGuard Extra, and TTV LOL PRO

I preferred AdGuard Extra's way of doing it by comparing the window Worker to an iframe Worker but under Firefox when opening streams in a new tab this lets ads leak through as workers can be created before the check
