### ISSUE TITLE
Plug-in no longer working?

### ISSUE THREAD

**Issue by djg007** [younesaassila/ttv-lol-pro#335]
Using the newest version of Firefox on the newest MacOS and currently just getting constant buffering when trying to watch a stream. Anyone else having this issue?

**Comment by Hunter4242** [comment]
I saw the same issue today on Windows 10, eventually the buffering stopped and then an ad played before the stream went on as usual. I've pasted the dev console log, hopefully what's in there will be helpful.

`Cookie “twitch.lohp.countryCode” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite smight
Loading failed for the <script> with source “https://d2v02itv0y9u9t.cloudfront.net/dist/1.1.7/v6s.js”. smight:1:1
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help https://xhr.spec.whatwg.org/#sync-warning p.js:1:148982
XML Parsing Error: not well-formed
Location: blob:https://www.twitch.tv/d243b25b-cf29-4b94-9056-15e6bffcaeee
Line Number 1, Column 14: d243b25b-cf29-4b94-9056-15e6bffcaeee:1:14
XML Parsing Error: not well-formed
Location: blob:https://www.twitch.tv/03f8b4ef-c6b6-4dc5-b991-d4a183c49217
Line Number 1, Column 14: 03f8b4ef-c6b6-4dc5-b991-d4a183c49217:1:14
[VideoTransformerModule]: Error, disabling module Error: WebGPU not available
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    e https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    h https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    C https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    I https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    init https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    e https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    h https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    C https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    I https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    init https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    e https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    h https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    C https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    I https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    init https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setupVideoTransformer https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    onConfigChanged https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    At https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setExperiment https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setExperimentData https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setExperimentData https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    R https://assets.twitch.tv/assets/core-153a1d96fb9e1efead6f.js:1
    D https://assets.twitch.tv/assets/core-153a1d96fb9e1efead6f.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    a https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
player-core-variant-a-bb035a988f0ca33d1284.js:1:107424
VideoTransformer error 
Object { code: -1000, source: "WebGPUContext", message: "WebGPU not available", fatal: true, gpu_architecture: "", gpu_description: "", gpu_device: "", gpu_vendor: "" }
player-core-variant-a-bb035a988f0ca33d1284.js:1:140289
[VideoTransformerModule]: Error, disabling module Error: WebGPU not available
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    e https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    h https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    C https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    I https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    init https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    e https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    h https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    C https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    I https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    init https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    e https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    h https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    C https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    I https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    init https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setupVideoTransformer https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    onConfigChanged https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    At https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setExperiment https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setExperimentData https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setExperimentData https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    R https://assets.twitch.tv/assets/core-153a1d96fb9e1efead6f.js:1
    D https://assets.twitch.tv/assets/core-153a1d96fb9e1efead6f.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    a https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
player-core-variant-a-bb035a988f0ca33d1284.js:1:107424
VideoTransformer error 
Object { code: -1000, source: "WebGPUContext", message: "WebGPU not available", fatal: true, gpu_architecture: "", gpu_description: "", gpu_device: "", gpu_vendor: "" }
player-core-variant-a-bb035a988f0ca33d1284.js:1:140289
Content-Security-Policy: The report URI (about:blank) should be an HTTP or HTTPS URI. smight
Content-Security-Policy: (Report-Only policy) The page’s settings would block a worker script (worker-src) at blob:https://www.twitch.tv/a9078e14-6f25-4e3a-84e8-f5cf5dea0c7d from being executed because it violates the following directive: “worker-src 'none'” smight
Content-Security-Policy: The report URI (about:blank) should be an HTTP or HTTPS URI. smight
Content-Security-Policy: (Report-Only policy) The page’s settings would block a worker script (worker-src) at blob:https://www.twitch.tv/f5c34b20-9f5d-4ede-8140-7d14e5d26e7c from being executed because it violates the following directive: “worker-src 'none'” smight
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! smight
Loading failed for the <script> with source “https://secure-ds.serving-sys.com/SemiCachedScripts/ebOneTag.js?id=1073745825&dataLayer=SizmekDataLayer&ptcl=https”. smight:1:1
Moving to buffered region 0.067 0 player-core-variant-a-bb035a988f0ca33d1284.js:1:41551
[VideoTransformerModule]: Error, disabling module Error: WebGPU not available
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    e https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    h https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    C https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    I https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    init https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    e https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    h https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    C https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    I https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    init https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    e https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    h https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    C https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    I https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    t https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    exports https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    init https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setupVideoTransformer https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    onConfigChanged https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    At https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setExperiment https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setExperimentData https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    setExperimentData https://assets.twitch.tv/assets/player-core-variant-a-bb035a988f0ca33d1284.js:1
    R https://assets.twitch.tv/assets/core-153a1d96fb9e1efead6f.js:1
    D https://assets.twitch.tv/assets/core-153a1d96fb9e1efead6f.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    s https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
    a https://assets.twitch.tv/assets/vendor-1a9a5e6365bb51d02545.js:1
player-core-variant-a-bb035a988f0ca33d1284.js:1:107424
VideoTransformer error 
Object { code: -1000, source: "WebGPUContext", message: "WebGPU not available", fatal: true, gpu_architecture: "", gpu_description: "", gpu_device: "", gpu_vendor: "" }
player-core-variant-a-bb035a988f0ca33d1284.js:1:140289
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sq-tungsten-ts.amazon-adsystem.com/noop?si=650&bidR=.4zwF0hsCqZ58VKAw90lkw&cb=7791582. (Reason: CORS request did not succeed). Status code: (null).

Loading failed for the <script> with source “https://www.twitch.tv/r/s/m/nat.min.js#_mApi6988216”. smight:1:1
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sq-tungsten-ts.amazon-adsystem.com/noop?si=650&bidR=.4zwF0hsCqZ58VKAw90lkw&cb=7791582. (Reason: CORS request did not succeed). Status code: (null).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Loading failed for the <script> with source “https://www.twitch.tv/r/s/m/nat.min.js#_mApi88887330”.`

**Comment by rdutta** [comment]
I've been unable to load any stream. If you are reading this, hello twitch devs you rats.

I've been using `multitwitch.tv/<channel_name>` as a workaround (still get purple screen every so often but its better than being inundated by ads).

**Comment by zGato** [comment]
Firefox public proxy load balancer is currently down. I'm unable to grab any information from the server and awaiting a response from my provider.

https://status.perfprod.com

Apologies for the inconveniences. Also do keep in mind ICMP is anycasted, thus pinging the server to see if it's online is pretty much useless.

**Comment by Espnandro** [comment]
> Firefox public proxy load balancer is currently down. I'm unable to grab any information from the server and awaiting a response from my provider.
> 
> https://status.perfprod.com
> 
> Apologies for the inconveniences. Also do keep in mind ICMP is anycasted, thus pinging the server to see if it's online is pretty much useless.

Any update on this? Currently not working for me on Firefox w11.
