### ISSUE TITLE
Add Octokit to check for GitHub updates on unpacked install.

### ISSUE THREAD

**Issue by NanoAi** [younesaassila/ttv-lol-pro#82]
Github has an API where you can check for updates to a repo with Javascript.
API: <https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28>
Octokit: <https://github.com/octokit/core.js>

Please add a passive update check that fires maybe once a day so users can stay up to date without having to edit their registry.

PS. How come this isn't on the app store? Project forks not allowed?

**Comment by younesaassila** [comment]
Thanks for your suggestion!

> Github has an API where you can check for updates to a repo with Javascript.

The extension already relies on an update URL for automatic updates. So, there would be no need to use the GitHub API.

> Please add a passive update check that fires maybe once a day so users can stay up to date without having to edit their registry.

This feature would require a new build system because the current one builds a unique version for all platforms.

> PS. How come this isn't on the app store? Project forks not allowed?

It's because Chrome no longer allows Manifest v2 extensions to be uploaded to their store.
