### ISSUE TITLE
Please provide option to ignore all channel subscriptions

### ISSUE THREAD

**Issue by karai17** [younesaassila/ttv-lol-pro#84]
Currently, TTV LOL Pro implicitly allows ads through for subscribed channels and provides an optional whitelist of channels to hide ads on. A checkbox that effectively disables this implicit "feature" would be handy. I don't want to see ads on *any* channel, subscribed or otherwise.

**Comment by younesaassila** [comment]
The reason this is the default behavior is that most channels don't show ads to subscribers. Proxying channels you are subbed to can show ads (since Twitch doesn't know you're subbed because of the proxy) and many people complained of seeing ads on subscribed channels.

I can add a toggle to disable this but I'm not sure it would be helpful for ad-blocking.

**Comment by EldritchEevee** [comment]
> The reason this is the default behavior is that most channels don't show ads to subscribers. Proxying channels you are subbed to can show ads (since Twitch doesn't know you're subbed because of the proxy) and many people complained of seeing ads on subscribed channels.
> 
> I can add a toggle to disable this but I'm not sure it would be helpful for ad-blocking.

This isn't possible without removing the entire addon, as it's queried every single frame (Firefox runs at your Monitor's refresh rate - ∞.)

**Comment by younesaassila** [comment]
> This isn't possible without removing the entire addon, as it's queried every single frame (Firefox runs at your Monitor's refresh rate - ∞.)
> 
> **In order to avoid desyncing your browser, you must disable ALL extensions.** Even things that aren't adblockers. External VPNs are included.

What are you talking about?
